In [40]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [41]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [42]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
ct = ColumnTransformer([("Geography", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)
X = X[:, 1:]

In [43]:
X[0]

array([0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [45]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [46]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [47]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [48]:
classifier = Sequential()

In [49]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',
                     input_dim=11))
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid',
                     ))
classifier.compile(optimizer='adam',loss="binary_crossentropy",metrics=['accuracy',])
classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100)

e:\anaconda\envs\python3.5\lib\site-packages\ipykernel_launcher.py:7: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  import sys


Epoch 1/100
8000/8000 [==============================] - 4s 462us/step - loss: 0.4901 - accuracy: 0.7955
Epoch 2/100
8000/8000 [==============================] - 2s 282us/step - loss: 0.4287 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 285us/step - loss: 0.4227 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 273us/step - loss: 0.4187 - accuracy: 0.8164
Epoch 5/100
8000/8000 [==============================] - 2s 263us/step - loss: 0.4163 - accuracy: 0.8259
Epoch 6/100
8000/8000 [==============================] - 2s 288us/step - loss: 0.4142 - accuracy: 0.8301
Epoch 7/100
8000/8000 [==============================] - 2s 275us/step - loss: 0.4128 - accuracy: 0.8296
Epoch 8/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4112 - accuracy: 0.8316
Epoch 9/100
8000/8000 [==============================] - 2s 230us/step - loss: 0.4101 - accuracy: 0.8335
Epoch 10/100
8000/8000 [==============================]

In [55]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1539   56]
 [ 250  155]]


In [56]:
(1539 +155)/2000

0.847